Update package model, Create application services
hhu-propra2/abschlussprojekt-teamymcteamface pull request #35
Opened 2020-03-11 11:46 UTC by smncrm

2020-03-11 18:53 UTC, MarcoSteinke requested changes
We will talk about the changes and maybe perform them tomorrow

2020-03-11 18:53 UTC, maste150hhu commented on src/main/java/mops/foren/applicationservices/PostService.java
> +    public void addPost(Post post, User user, Long threadId) {
Look into branch "permissions-and-new-domain-model". I wrapped the Id's so the Method checkPermission will know if the id is a ThreadId or ForumId.

2020-03-11 18:53 UTC, maste150hhu commented on src/main/java/mops/foren/applicationservices/ThreadService.java
> +    public void addThread(Thread thread, User user, Long topicId) {
Look into branch "permissions-and-new-domain-model". I wrapped the Id's so the Method checkPermission will know if the id is a ThreadId or ForumId.

2020-03-11 18:53 UTC, maste150hhu commented on src/main/java/mops/foren/applicationservices/TopicService.java
> +    public void addTopic(Topic topic, User user, Long forumId) {
Look into branch "permissions-and-new-domain-model". I wrapped the Id's so the Method checkPermission will know if the id is a ThreadId or ForumId.

2020-03-11 18:53 UTC, maste150hhu commented on src/main/java/mops/foren/domain/model/User.java
> +    private HashMap<Long, Permission> permissons;
In the branch "permissions-and-new-domain-model" I got to implement a permission-system which suits this storage of permissions inside of a HashMap. The next step would be to implement a PermissionService, which checks the user-permission on security-related events.

2020-03-12 08:33 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/Forum.java
> +    private ForumId id;
make this id variable final please

2020-03-12 08:35 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/ForumId.java
> +    private Long id;
make this variable final please

2020-03-12 08:36 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/Post.java
> +    private PostId id;
final please

2020-03-12 08:37 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/Post.java
> +    private ThreadId threadId;
final please

2020-03-12 08:37 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/PostId.java
> +    private Long id;
final please

2020-03-12 08:38 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/Thread.java
> +    private TopicId topicId;
final please

2020-03-12 08:38 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/ThreadId.java
> +    private Long id;
final please

2020-03-12 08:38 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/Topic.java
> +    private ForumId forumId;
final please

2020-03-12 09:12 UTC, mgtgecko approved these changes
Läuft.

2020-03-12 09:13 UTC, mgtgecko approved these changes

2020-03-12 09:15 UTC, MarcoSteinke approved these changes

2020-03-12 09:16 UTC, merged