First full draft
hhu-propra2/abschlussprojekt-teamymcteamface pull request #41
Opened 2020-03-13 16:53 UTC by TuringRs

2020-03-16 09:51 UTC, SherinSchneider commented
Was ist mit diesem PR? Mag mir jemand was dazu erzählen? Der scheint ja noch von Freitag zu sein.

2020-03-16 10:06 UTC, TuringRs commented
Wird grade reviewed und hoffentlich gleich gemerged.

2020-03-16 13:02 UTC, niruc100 requested changes
please refactor

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/applicationservices/UserService.java
> +    public boolean checkIfUserIsExistent(User user) {
renaming

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/domain/model/User.java
> +    }
notwendig?

2020-03-16 13:02 UTC, niruc100 commented on config/checkstyle/checkstyle.xml
>  </module>
bitte entfernen

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/mapper/ForumMapper.java
> +    }
rename please

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/repositories/ForumJpaRepository.java
> +
please delete

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/repositories/ForumRepositoryImpl.java
> +    }
renaming

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/repositories/UserRepositoryImpl.java
> +        this.userRepository = userRepository;
add new line instead of suppression of warnings

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/repositories/UserRepositoryImpl.java
> +    public boolean isUserExistent(User user) {
microtype Boolean

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/persistence/repositories/UserRepositoryImpl.java
> +    public void updateUser(User user, Forum forum) {
renaming

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/web/ForumForm.java
> +    public Forum map() {
renaming

2020-03-16 13:02 UTC, niruc100 commented on src/main/resources/application.properties
> +spring.security.user.roles=ADMIN
please delete this

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/web/ForenController.java
> +    @SuppressWarnings("LineLength")
please delete

2020-03-16 13:02 UTC, niruc100 commented on src/main/java/mops/foren/infrastructure/web/ForenController.java
> +    }
please refactor this into a new class

2020-03-17 07:59 UTC, niruc100 approved these changes

2020-03-17 08:13 UTC, smncrm commented
Wollt ihr den mergen trotz der fehlschlagenden Tests ?

2020-03-17 08:37 UTC, merged